# Generated by Django 3.2.13 on 2023-09-06 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedothiago', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela',
            old_name='elenco',
            new_name='cor',
        ),
    ]
