# Generated by Django 3.2.13 on 2023-09-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedothiago', '0003_alter_motivosarabia_dinheiro_colocado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivosarabia',
            name='dinheiro_colocado',
            field=models.CharField(max_length=10000),
        ),
    ]
